language: python

python:
  - 3.6

cache: pip

script:
- echo "Hello!"

before_deploy:
- |
  # Install git-crypt
  curl -L https://github.com/minrk/git-crypt-bin/releases/download/0.5.0/git-crypt > git-crypt
  echo "46c288cc849c23a28239de3386c6050e5c7d7acd50b1d0248d86e6efff09c61b  git-crypt" | shasum -a 256 -c -
  chmod +x git-crypt
  mv git-crypt ${HOME}/bin/git-crypt
- openssl aes-256-cbc -K $encrypted_12b31592d0a4_key -iv $encrypted_12b31592d0a4_iv
  -in git-crypt.key.enc -out git-crypt.key -d
- |
  # Unlock our secret files!
  # Travis allows encrypting only one file per repo (boo) so we use it to
  # encrypt our git-crypt key
  git-crypt unlock git-crypt.key
